spring:
  profiles:
    default: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db,diskSpace

jwt:
  expiration: 86400000

ai:
  server:
    base-url: https://ai.swe.bluerack.org
