spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

app:
  api-server-url: ${API_SERVER_URL:https://api.swe.bluerack.org}
